# Generated by Django 2.2 on 2019-04-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.CharField(max_length=200)),
                ('initiative_value', models.IntegerField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initiative_tracker.Encounter')),
            ],
        ),
    ]
